title: Kyle Ratti
email: hi@kyleratti.me
author: Kyle Ratti
description: >-
  An inside look at my mind, my projects,
  things I've done, things I want to do,
  and thoughts I want to share with the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kyleratti.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username: kyleratti
timezone: America/New_York

target-blank:
  add_css_classes: extLink

markdown: kramdown
highlighter: rouge

# Build settings
theme: minima
plugins:
  - jekyll-target-blank
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
